- apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main
    state: present

- apt:
    name=postgresql-10 state=latest

- service:
    name=postgresql state=started enabled=yes
